### ISSUE TITLE
create a Lisense with a trial software key

### ISSUE THREAD

**Issue by kanezjm** [lemonce/probe-client#34]
- [ ] add a gui window which users can enter their key
- [x] find unique thing (probably BIOS, UUID, or Identifying Number) about user's operating system. https://github.com/lemonce/probe-client/commit/ce04772562f8dfd0c86e3daf486506f70028bea4
- [ ] implement key validation and caching.  
  experimental validation: https://github.com/lemonce/probe-client/commit/c65c53de2472160c8d1fc1277f9ecf3e5c63c7d0

**Comment by steambap** [comment]
Close it for now since it's not important
