### ISSUE TITLE
auto-generate notes too short in English

### ISSUE THREAD

**Issue by kanezjm** [lemonce/probe-client#59]
`#AUTOWAIT 500
#TIMES 1

process main () {
	// Google
	jumpto "https://www.google.com/";
	wait 555;
	// click a text field
	click "#lst-ib";
	// click Google Sear...
	click "div.jsb > center:nth-child(1) > input:nth-child(1)";
	// click I'm Feeling...
	click "div.gbqfba > div:nth-child(1) > div:nth-child(3) > span:nth-child(1)";
}`

**Comment by steambap** [comment]
ba77a1f32990bc742293210b3312d559410fa603
