### ISSUE TITLE
Add windows Installer distribute

### ISSUE THREAD

**Issue by lichaozhy** [lemonce/probe-client#9]
- [x] Add context menu to folder
- [x] Add app icon
- [x] learn *.iss
- [ ] Exclude source code & simplify directory

**Comment by steambap** [comment]
http://www.jrsoftware.org/ishelp/index.php?topic=examples

**Comment by steambap** [comment]
here is another installer that support auto update:  
https://github.com/electron-userland/electron-builder

**Comment by lichaozhy** [comment]
Can electron-builder use to register contextmenu?

**Comment by steambap** [comment]
no

**Comment by steambap** [comment]
https://github.com/lemonce/probe-client/commit/523301bb9c66ec2762f545e67b949427cf2c1e4f
